[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/dev/null


[program:php-fpm]
command=/usr/local/sbin/php-fpm
stdout_logfile=/dev/null
stderr_logfile=/dev/null
autostart=true
autorestart=true
priority=10

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
stdout_logfile=/dev/null
stderr_logfile=/dev/null
autostart=true
autorestart=true
priority=20